# Generated by Django 4.2.4 on 2023-08-23 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='file',
        ),
    ]
